name: Continuous Integration
on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '*.txt'
      - LICENSE
      - .editorconfig
      - .*ignore
      - .vscode
    tags-ignore: ['*']
  pull_request:
    branches: ['*']
    paths-ignore:
      - '*.md'
      - '*.txt'
      - LICENSE
      - .editorconfig
      - .*ignore
      - .vscode

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v15
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint
