name: Release Please
on:
  push:
    branches: [main]

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          pull-request-title-pattern: 'chore${scope}: release${component} v${version}'
          bump-minor-pre-major: true

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Use Node.js v15
        uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        run: yarn install --immutable
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to NPM
        run: yarn npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
